# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaskAgent < Formula
  desc "YOLO AI Task Executor for Asana — Bubble Tea TUI"
  homepage "https://github.com/TheCoolRobot/task-agent"
  version "0.1.31"
  license "MIT"

  depends_on "thecoolrobot/asana-cli/asana-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.31/task-agent_darwin_x86_64.tar.gz"
      sha256 "cedb556651b347c5579959894b22be8cc6462da38e20780adc0da08a27783456"

      def install
        bin.install "task-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.31/task-agent_darwin_arm64.tar.gz"
      sha256 "72f9dfb0ca773ba98b198bdda8d9b9612760e1b07dec8ff112946e69da757865"

      def install
        bin.install "task-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.31/task-agent_linux_x86_64.tar.gz"
      sha256 "5529abf571b4b69fbc0f45f7288e0b319645efc9495a90c54896c014cd8dad59"
      def install
        bin.install "task-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.31/task-agent_linux_arm64.tar.gz"
      sha256 "6af01e2e51d9be057b9ca531aa3bc016ebdefc9ddd8de58627712b394a49842a"
      def install
        bin.install "task-agent"
      end
    end
  end

  test do
    system "#{bin}/task-agent", "--version"
  end
end
