# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaskAgent < Formula
  desc "YOLO AI Task Executor for Asana — Bubble Tea TUI"
  homepage "https://github.com/TheCoolRobot/task-agent"
  version "0.1.0-beta"
  license "MIT"

  depends_on "thecoolrobot/asana-cli/asana-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.0-beta/task-agent_darwin_x86_64.tar.gz"
      sha256 "5b826522cbc6ca094973efc4f200099faf963a770821ea913d84cd7169ba20f7"

      def install
        bin.install "task-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.0-beta/task-agent_darwin_arm64.tar.gz"
      sha256 "e56d2465b56092bad1cf2c6f93c471e39af6a54bf5e0e33fd33b081f4c63b8c7"

      def install
        bin.install "task-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.0-beta/task-agent_linux_x86_64.tar.gz"
      sha256 "9de71d62cfdb6ca8d76e150f16e6c7b8eca1ee263cfdaf461214fadd42641beb"
      def install
        bin.install "task-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheCoolRobot/task-agent/releases/download/v0.1.0-beta/task-agent_linux_arm64.tar.gz"
      sha256 "d2eb1f9cea5773803a482aa831b0c7df69ab0102007878648482ac02a9d7644b"
      def install
        bin.install "task-agent"
      end
    end
  end

  test do
    system "#{bin}/task-agent", "--version"
  end
end
